### ISSUE TITLE
Errors trying to use this github

### ISSUE THREAD

**Issue by Jorgecanetemartin** [LukasBenner/AASFix#22]
Hello, I am trying to update my v3 aasx with your github, but I can't run it as you said in your explanation.
When I try to use the command of AASFix it does not execute anything.(The error is in Spanish but bassicaly says that it does not find that)

![image](https://github.com/LukasBenner/AASFix/assets/62398794/98dbce2a-08a2-4607-81a3-ff254f3296da)

I tried to run other of your files and it runs it but it does not get any output.

![image](https://github.com/LukasBenner/AASFix/assets/62398794/c23e2da4-860c-42cc-939b-d86863fee57a)

![image](https://github.com/LukasBenner/AASFix/assets/62398794/62e757b2-aee9-45ed-a382-9d2e183afced)

How can I use this github to solve my 5G UE AAS.aasx file problems?

**Comment by WelliSolutions** [comment]
To me it seems that you have downloaded the Source Code (because I see you have a `src` directory).
`.cs` files are C# source code files and cannot be run.
Please download the binaries from https://github.com/LukasBenner/AASFix/releases/

If you have spaces in your file name, like `5G UE AAS.aasx`, use quotation marks around the file name:  `"5G UE AAS.aasx"`
